### ISSUE TITLE
Get the tutorial site ready for "official" launch (meta for 1.0)

### ISSUE THREAD

**Issue by OceanWolf** [scribusproject/scribus-tutorials#13]
A minimal meta-issue to track issues that need to get resolved before we begin shouting about it, aka a version 1.0 of the site.
- [ ] A newsletter system in place to announce it on
- [ ] Ideas from the community to help shape it from the beginning (Questionnaire)
- [ ] An actual tutorial (rather than just meta tutorials)
- [x] A footer for the license
- [ ] Switch from hash nav to hashbang nav (#foo -> #!foo)
